### ISSUE TITLE
Logo PRoporsal

### ISSUE THREAD

**Issue by LuigiBaute** [leegeunhyeok/visual-electron#1]
Greetings @leegeunhyeok  ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by leegeunhyeok** [comment]
Hello @LuigiBaute ,
(I'm not good at English. I hope you can understand me)

Thank you for your positive evaluation of my project :)

Your suggestion is interesting to me!
I did not know much about design, so I always had a lot of problems when creating a resource.(logo, icon etc..)

I am interested in your proposal!

Thank you,
-Geunhyeok LEE

**Comment by LuigiBaute** [comment]
Great @leegeunhyeok !

Your english its perfectly understandable to me!

Before proceeding towards the logo-making process I'd like to ask you some questions:

What's the name that should be displayed on the logo/icon ?

What's the purpose/goal of this project ? (details of the project can work too) 

What's the message you would like the logo/icon to transmit?

I'll be looking forward to your reply! hopefully something good can come out of this work!

**Comment by leegeunhyeok** [comment]
Greetings @LuigiBaute ,

Thank you for your comment.

This is answer of your questions: 
- Name : Visual Electron
- Purpose of project: Data visualization(Create various kinds of chart), save, load ..etc 
- Message of logo/icon: Chart icon OR like a eye icon (Visualization emphasis)

and Project's main text color is : #a2ecfb

Have a good day :)
-Geunhyeok LEE

**Comment by LuigiBaute** [comment]
Hey @leegeunhyeok ,
This is a sample of what I had in mind,
it can be adjusted however you want, 
I'll wait for your feedback!
hope you like it.
![logotipo visual electron](https://user-images.githubusercontent.com/36426974/41215280-9beaea38-6d1d-11e8-90b8-2725a92245a9.png)

**Comment by leegeunhyeok** [comment]
Hello @LuigiBaute ,

Your logo design is awesome! 👍 

I like 3rd, 4th logo. (2 row logos)
I want use that logo

Thank you for your work :)


All the best,
Geunhyeok LEE

**Comment by LuigiBaute** [comment]
Great, should I submit a pull request with the 3rd or 4th or both?
-if so, where should I upload the files,
 besides that I'll submit a google drive link with its monochromatic versions and in a pdf, .png, .svg, cdr files.
I'll look forward for your feedback

**Comment by leegeunhyeok** [comment]
Add logo(4th logo) to README.md and PR please :)

If you give a logo link, I'll add logo in program and project info.

**Comment by LuigiBaute** [comment]
the [pull request](#2) has been made @leegeunhyeok ,
I've also submitted the google drive link with all the ready to use files, monochromatics, png, pdf, cdr, svg.
for any futures updates! :+1:

**Comment by leegeunhyeok** [comment]
Thanks @LuigiBaute ,

Successfully Merged your PR 👍 
I will finish this project :)
